services:
  data-collector:
    build: ./metrics-backend/data-collector  # 경로 수정
    container_name: data-collector
    environment:
      - spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER}
      - TZ=Asia/Seoul
    networks:
      - monitoring_network

  localhost-data-collector:
    build: ./metrics-backend/localhost-data-collector  # 경로 수정
    container_name: localhost-data-collector
    environment:
    - spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER}
    - TZ=Asia/Seoul
    networks:
      - monitoring_network
networks:
  monitoring_network:
    external: true