version: '3'
services:
  data-collector:
    build: .
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - metrics-backend_default

networks:
  metrics-backend_default:
    external: true
